#!/usr/bin/env node
 
/**
 * Module dependencies.
 */
 
var program = require('commander');

function tryval(val) {
    return 'your value is' + val;
}

function list(val) {
  return val.split(',');
}
 
program
  .version('0.0.1')
  .option('-p, --peppers', 'Add peppers')
  .option('-P, --pineapple', 'Add pineapple')
  .option('-b, --bbq-sauce', 'Add bbq sauce')
  .option('-v, --vvv <value>','try function', tryval)
  .option('-l, --list <items>', 'A list', list)
  .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
  .parse(process.argv);
 
console.log('you ordered a pizza with:');
if (program.peppers) console.log('  - peppers');
if (program.pineapple) console.log('  - pineapple');
if (program.bbqSauce) console.log('  - bbq');
console.log('value is: %s', program.vvv);
console.log(' list: %j', program.list);
console.log('  - %s cheese', program.cheese);